---
### Install, this install only target to ubuntu 14.04

- name: Ensure that APT works with the https method, and that CA certificates are installed
  package: name={{ item }} state=present
  with_items:
    - apt-transport-https
    - ca-certificates

# if http proxy needed, add the following.
# {% if http_proxy is defined -%}--keyserver-options http-proxy={{ http_proxy }} {% endif -%}
- name: Install GPG key
  apt_key:
    keyserver: 'hkp://p80.pool.sks-keyservers.net:80'
    id: 58118E89F3A912897C070ADBF76221572C52609D

- name: Configure apt repository
  template: src="docker.list.j2" dest="/etc/apt/sources.list.d/docker.list"
  register: add_apt_source_docker
- name: Update repository information
  apt:
    update_cache: yes
  when: add_apt_source_docker.changed

- name: Purge old docker if it exists
  package:
    name: lxc-docker
    state: absent

- name: Ensure linux-image-extra-* kernel packages installed
  package:
    name: "{{ item }}"
    state: present
  items:
    - "linux-image-extra-{{ ansible_kernel }}"
    - linux-image-extra-virtual
